name: CI
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        ghc:
        - '8.6.5'
        - '8.8.4'
        - '8.10.7'
        - '9.0.1'
        - '9.1.1'
        os:
        - ubuntu-latest
        # TODO: - windows-latest
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/cache@v1
      name: Cache ~/.cabal/store
      with:
        path: ~/.cabal/store
        key: cabal-store-${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('arbtt.cabal') }}
        restore-keys: cabal-store-${{ runner.os }}-${{ matrix.ghc }}-

    - uses: actions/checkout@v2
    - uses: haskell/actions/setup@v1
      with:
        ghc-version: ${{ matrix.ghc }}

    - if: runner.os == 'Linux'
      run: sudo apt-get install libxss-dev libx11-dev libxrandr-dev libxinerama-dev
    - name: Build
      run: |
        cabal update
        cabal build -w ghc-${{ matrix.ghc }}
        cabal test -w ghc-${{ matrix.ghc }}

  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt-get install xsltproc docbook-xsl
    - name: Build
      run: |
        make -C doc html
        mkdir -p website/doc
        mv doc/users_guide website/doc
        touch website/.nojekyll
    - name: Deploy to Github Pages
      if: github.ref == 'refs/heads/master'
      uses: JamesIves/github-pages-deploy-action@4.1.3
      with:
        BRANCH: gh-pages
        FOLDER: website
        SINGLE-COMMIT: true

