name: CI
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        ghc:
        - '8.6.5'
        - '8.8.4'
        - '8.10.2'
        os:
        - ubuntu-latest
        - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/cache@v1
      name: Cache ~/.cabal/store
      with:
        path: ~/.cabal/store
        key: cabal-${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project', 'cabal.project.freeze') }}
        restore-keys: cabal-${{ runner.os }}-${{ matrix.ghc }}-

    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: ${{ matrix.ghc }}
    - name: Build
      run: |
        ls -l /opt/ghc/
        export PATH=/opt/ghc/bin:$PATH
        cabal --version
        ghc --version
        cabal update
        cabal build
        cabal build -w ghc-${{ matrix.ghc }}
        cabal test -w ghc-${{ matrix.ghc }}

  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt-get install xsltproc docbook-xsl
    - name: Build
      run: |
        make -C doc html
        mkdir -p website/doc
        mv doc/users_guide website/doc
        touch website/.nojekyll
    - name: Deploy to Github Pages
      if: github.ref == 'refs/heads/master'
      uses: JamesIves/github-pages-deploy-action@4.1.3
      with:
        BRANCH: gh-pages
        FOLDER: webiste
        SINGLE-COMMIT: true

